matrix:
  include:
    - os: linux
      dist: bionic

language: python

install:
  - pip install -r requirements.txt

script:
  - pytest  --cov-report term --cov=./pyExplore/

after_success:
  - codecov